### PR TITLE
Download_NDNC_buoy_data

### PR DESCRIPTION
**Pull request by daniel-caichac-DHI**
Added a notebook to download NDBC data
@jsmariegaard

### CODE REVIEW

**Comment by jsmariegaard** [comment]
@daniel-caichac-DHI was it intentional that you closed this PR without merging?

**Comment by daniel-caichac-DHI** [comment]
I created a PR by mistake actually, I thought you just wanted the notebook. Although I think is decent enough for a PR anyway

**Comment by jsmariegaard** [comment]
@daniel-caichac-DHI I will update this a bit and then merge - if okay with you?

**Comment by daniel-caichac-DHI** [comment]
Yes, good with me

**Pull request merged**
